### ISSUE TITLE
model crashes on load

### ISSUE THREAD

**Issue by malnemark** [DSD-DBS/py-capellambse#153]
Hello,

I encountered an issue loading a model in which I use custom colors for functions. This morning the load failed with the following trace: 

```
model = capellambse.MelodyModel(path_to_model, jupyter_untrusted=True)

model

---------------------------------------------------------------------------
CorruptModelError                         Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 model = capellambse.MelodyModel(path_to_model, jupyter_untrusted=True)
      2 model

File C:\Python3.9.10\lib\site-packages\capellambse\model\__init__.py:182, in MelodyModel.__init__(self, path, diagram_cache, diagram_cache_subdir, jupyter_untrusted, **kwargs)
     77 """Load a project.
     78 
     79 For complete information on which exact ``kwargs`` are
   (...)
    178     A simple ``http(s)://`` file handler.
    179 """
    180 capellambse.load_model_extensions()
--> 182 self._loader = loader.MelodyLoader(path, **kwargs)
    183 self.info = self._loader.get_model_info()
    184 self.jupyter_untrusted = jupyter_untrusted

...

File C:\Python3.9.10\lib\site-packages\capellambse\loader\core.py:185, in ModelFile.idcache_index(self, subtree)
    183     existing = self.__idcache.get(elm_id)
    184     if existing is not None and existing is not elm:
--> 185         raise CorruptModelError(
    186             f"Duplicate UUID {elm_id!r}"
    187             f" within fragment {self.filename!s}"
    188         )
    189     self.__idcache[elm_id] = elm
    191 href = elm.get("href")

CorruptModelError: Duplicate UUID '_7YPiIDmfEe2NS4yZ4XQFdA' within fragment MyProject.aird
```

Duplicate UIDs appear now pairwise in many places (even those without styles) in the .aird file and the model loading interrupts. Capella still opens the model fine. 

![grafik](https://user-images.githubusercontent.com/485955/193207726-0100c60a-c937-4c74-877e-efd3da726852.png)

**Comment by Wuestengecko** [comment]
> Capella's Repair command isn't working on the `.capella`(`.melodymodeller`) file but just the `.aird` file.

That would enough in this case however - the immediate issue here is in the `MyProject.aird` file. @malnemark could you try Capella's built-in repair function first?

**Comment by malnemark** [comment]
The repair unfortunately didnt fix the issue.

**Comment by Wuestengecko** [comment]
As it turns out, occasional random duplication of UUIDs between model elements is a known issue with Capella. Unfortunately there's no fix for that (yet), and there's also currently no reliable way to automatically fix models after the issue has occurred.

Luckily if it happens in the `.aird` files it's much less dramatic than the `.capella` files. In most cases, you can simply open the `MyProject.aird` with a text editor, search for the offending ID (`_7YPiIDmfEe2NS4yZ4XQFdA`), and add numbers at the end - worst case you could lose a diagram, which you'd have to delete and recreate manually, but even then the semantic model isn't affected and you can simply drag all the objects you need into the diagram view again.

It's likely that you'll have multiple collisions in your model, but capellambse will only show the first one it finds. So you'll have to try to load the model multiple times and fix each collision as it's discovered. And if you do end up finding one in a `.capella` file, you're probably better off trying to delete one of the offending objects in Capella and recreating it, which should then assign a new, random UUID (which hopefully isn't already assigned this time).

Note that capellambse does also include additional code which ensures that generated UUIDs are actually always unique across a model, so if you use it to create objects in your semantic model you should never be able to run into this issue.

**Comment by Wuestengecko** [comment]
Hey! Sorry for not coming back to you here sooner.

In the meantime, we've added a load time parameter which allows you to ignore UUID duplication and load the model anyways (which is essentially the behavior from before the dup check was added). Here's an example:

```python
model = capellambse.MelodyModel(
    path_to_model,
    jupyter_untrusted=True,
    ignore_duplicate_uuids_and_void_all_warranties=True,
)
```

As this is not really an issue with capellambse but rather the model you're using, I'll mark this issue as done now. If you have any other questions, feel free to open a new issue or discussion.
