### ISSUE TITLE
Association edge_factory

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/py-capellambse#20]
A really weird thing that happened during development of Association factory:
Normally we define a special factory function and try to reuse the **generic_factory**, since this already gets almost everything done. Most special factories just deal with the labels that should appear.

With associations in class diagrams it's a bit different:
Here we have to deal with multiple(I think it's at maximum 2) labels that are specifying the rolenames. I tried following changes to the aird.diagram.Edge:
![image](https://user-images.githubusercontent.com/50786483/141154805-02981af6-133a-44e8-a6da-c9670a68c6ad.png)
Edges now have label**s** that default to an empty sequence.

This wasn't explicitly handed over in the generic factory and caused repetition of all preceeding edge.labels in the newly constructed edge... almost like the edge wasn't constructed freshly, just reused.

I'd really like to understand how this could happen in my favourite programming language.

What fixed the issue:
![image](https://user-images.githubusercontent.com/50786483/141154932-16967f38-7b62-49a6-8325-9c42cf9e2f31.png)

**Comment by Wuestengecko** [comment]
>     labels: t.Sequence[Box] = [],

Here's the issue. If you use a mutable default value as function argument, the modifications persist, because it's the same list that gets passed in every time the function/method is called.

Instead, use `None` as the default and use something similar to this at the start of the function body:

```
if labels is None:
    labels = []
```

(It might be a good idea in general to enable `pylint` automatic checking, because IIRC it actually warns you about this exact issue.)
