### ISSUE TITLE
`capellacommon.State.functions` always empty (model.search broken?)

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/py-capellambse#358]
The function attribute on a `State` is declared with the ReferenceSearchingAccessor. That is correct since in the `.capella` file functions may have an `availableInStates` attribute which is accessible via `available_in_states` on a class inheriting from `AbstractFunction`. Yet still `.functions` will always return an empty `c.ElementList`. Looking at the `__get__` method on the ReferenceSearchingAccessor:
```python
def __get__(self, obj, objtype=None):
        ...
        matches: list[etree._Element] = []
        for candidate in obj._model.search(*self.target_classes):
            ...
```

`model.search` is called with `self.target_classes` which can include types declared in py-capellambse's model module but don't own an xtype in Capella. The search function needs to be fixed such that it can resolve classes which only exist in `capellambse.model` for grouping attributes and reducing lines of code. Is it right, that all classes that have the `None` key in the `XTYPE_HANDLERS` are of such kind, i.e. they don't own a real xtype? I'd suggest to extend the search method to find all class types from the non-`None` key `XTYPE_HANDLERS` which are inheriting from the `self.target_classes`.

What do you think?

**Comment by Wuestengecko** [comment]
I don't think `model.search()` is broken, but the way that `States.functions` currently uses it is.

As of right now, `model.search()` doesn't support abstract types and subclasses, so the correct usage would be to list out the concrete types we expect to see (i.e. OperationalActivity and System-/Logical-/PhysicalFunction).

We could think about extending `model.search()` to also perform subclass checks, but since it's one of the more heavily used frontend methods we also need to take care that we don't impact performance too much with that.

I have too much on my plate to worry about that right now (so I'd just fix `States.functions`), but feel free to try it and report back how well it runs. :)
