### ISSUE TITLE
Undefined nature of root physical component causes KeyError on access attempt

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/py-capellambse#41]
Physical components are supposed to have `nature` attribute, however for root physical component this attribute is undefined. Current impolementation assumes it is always defined and expects the value to match an enum. This failes with key error.

The issue can be reproduced on the test model `5_0` with the following code: `model.pa.all_components[0].nature`

![image](https://user-images.githubusercontent.com/8280844/145726320-92aa8ac7-4602-49a2-b999-81edaf0c8f9d.png)

**Comment by Wuestengecko** [comment]
I'm a little unhappy with the resolution to this issue.

Obviously crashing when trying to access attributes on the root component is not an option, I absolutely agree with that. But I don't think it's a good idea to introduce an arbitrary new "dummy value" and use it as fallback. This suggests to a user who isn't familiar with the meta-model that it's actually okay to set that value on any component. Our validation logic will let that through without complaints, since the value is now registered in the underlying enum. However, the Capella GUI does not offer UNSET as a selectable option for NATURE (unlike KIND, where it does), as you can see here:

![Capella GUI showing Kind and Nature selection boxes](https://user-images.githubusercontent.com/1579756/147762514-72b4feda-b4f4-46b0-a9f2-9ed29e4e5f0a.png)

If you remove the `nature="..."` attribute from the XML using a text editor (or by assigning `UNSET` to `.nature` after d4df26303c0c946915ed6e667d17a538de150bf9), the component sort of breaks in Capella. It becomes grey in diagrams (instead of yellow or blue), and because you can't change a component's "Nature" via GUI anyways, you also can't repair it that way.

Therefore I think it would be a better idea to change the `EnumAttributeProperty`'s behavior in the "absent and no default" case from "raise an exception" to "return None", and to remove the dummy value "UNSET" from the enum of accepted values again. This would be far more graceful than raising a `KeyError(None)` into client code, yet it won't allow setting values that shouldn't be settable.

Summoning @ewuerger back for discussion.

**Comment by ewuerger** [comment]
I think your arguments are well layed out and I can only agree to your proposed solution. Having an unset enum value defined on the Nature of physical components is an unnecessary deviation from the actual metamodel and happened due to me only interested in removing the KeyError raising. 
I've wrongly taken the kind enum as a template to solve this. But implementing your proposed behaviour should be fairly trivial now(Assuming the default parameter takes None). 

Since we want to come as close to the behaviour that the user experiences via the GUI, with reasoning onto avoiding possible model corruption or disabling of modified model elements and their properties, I additionally propose to tell the user that it is prohibited to change the Kind property value to something else than None. This can happen via simply raising a ValueError.

Then how does one recognize programatically that certain properties are disabled? Is this information somewhere in the xml(I've never encountered this) or do we get this with using the py4capella implementation? Something to trs and think about for the successing issues.
